version: '3.8'
services:
  langgraph-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langgraph-agentic-ai
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./AINews:/app/AINews
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
